name: HexTools
main: net.spacegeek224.hextools.HexTools
version: 0.0.1
author: spacegeek224
commands:
  help:
    description: Get help
    usage: /help [topic]
    permission: hex.tools.help
  report:
    description: Report a player.
    usage: /report <player> <reason>
    permission: hex.tools.report
  shout:
    description: Shout something.
    usage: /shout <message>
    permission: hex.tools.shout
  bug:
    description: File a bug report.
    usage: /bug <description>
    permission: hex.tools.bug
